# Generated by Django 4.2.6 on 2023-11-25 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 22, 33, 9, 847176, tzinfo=datetime.timezone.utc)),
        ),
    ]
